select PHOTO_POST.POST_ID, PHOTO_POST.DESCRIPTION,  PHOTO_POST.CREATION_DATE, USER.NAME
FROM PHOTO_POST
inner join USER on USER.USER_ID = PHOTO_POST.USER_ID
group by PHOTO_POST.DESCRIPTION
having length(PHOTO_POST.DESCRIPTION) > 100;