-- MySQL Script generated by MySQL Workbench
-- Sat May 25 17:26:00 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema PhotoPortal
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema PhotoPortal
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `PhotoPortal` DEFAULT CHARACTER SET utf8 ;
USE `PhotoPortal` ;

-- -----------------------------------------------------
-- Table `PhotoPortal`.`USER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PhotoPortal`.`USER` (
  `USER_ID` INT NOT NULL,
  `NAME` VARCHAR(45) NULL,
  PRIMARY KEY (`USER_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PhotoPortal`.`PHOTO_POST`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PhotoPortal`.`PHOTO_POST` (
  `POST_ID` INT NOT NULL,
  `DESCRIPTION` VARCHAR(100) NULL,
  `CREATION_DATE` VARCHAR(45) NULL,
  `PHOTO_LINK` VARCHAR(45) NULL,
  `LIKES` VARCHAR(45) NULL,
  `HASHTAGS` VARCHAR(45) NULL,
  `USER_ID` INT NULL,
  PRIMARY KEY (`POST_ID`),
  INDEX `USER_ID_idx` (`USER_ID` ASC) VISIBLE,
  CONSTRAINT `USER_ID`
    FOREIGN KEY (`USER_ID`)
    REFERENCES `PhotoPortal`.`USER` (`USER_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
